<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="11" total="22" passed="11" failed="0" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-07-15T18:06:49 MSK" name="Default suite" finished-at="2021-07-15T18:06:50 MSK" duration-ms="803">
    <groups>
    </groups>
    <test started-at="2021-07-15T18:06:49 MSK" name="Default test" finished-at="2021-07-15T18:06:50 MSK" duration-ms="803">
      <class name="by.training.task06.service.ThreadServiceTest">
        <test-method signature="threadLongAdderActionNegativeTest(java.lang.String,int,java.lang.String,int)[pri:0, instance:by.training.task06.service.ThreadServiceTest@66565121]" started-at="2021-07-15T18:06:50 MSK" name="threadLongAdderActionNegativeTest" description="negative for threadLongAdderAction" data-provider="NegativeForThreadService" finished-at="2021-07-15T18:06:50 MSK" duration-ms="98" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[D:\javaSt2021\task06//src//main//resources//arrayWrong1.txt]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[200]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[D:\javaSt2021\task06//src//main//resources//threads.txt]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[10]]>
              </value>
            </param>
          </params>
          <exception class="by.training.task06.service.ServiceException">
            <message>
              <![CDATA[wrong_data_in_file]]>
            </message>
            <full-stacktrace>
              <![CDATA[by.training.task06.service.ServiceException: wrong_data_in_file
at by.training.task06.service.InitiateMatrixImpl.createMatrixMemberFromString(InitiateMatrixImpl.java:85)
at by.training.task06.service.InitiateMatrixImpl.takeMatrixFromFile(InitiateMatrixImpl.java:61)
at by.training.task06.service.ThreadLongAdderService.threadLongAdderAction(ThreadLongAdderService.java:49)
at by.training.task06.service.ThreadServiceTest.threadLongAdderActionNegativeTest(ThreadServiceTest.java:126)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- by.training.task06.service.ServiceException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- threadLongAdderActionNegativeTest -->
        <test-method signature="threadLongAdderActionNegativeTest(java.lang.String,int,java.lang.String,int)[pri:0, instance:by.training.task06.service.ThreadServiceTest@66565121]" started-at="2021-07-15T18:06:50 MSK" name="threadLongAdderActionNegativeTest" description="negative for threadLongAdderAction" data-provider="NegativeForThreadService" finished-at="2021-07-15T18:06:50 MSK" duration-ms="96" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[D:\javaSt2021\task06//src//main//resources//arrayWrong2.txt]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[200]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[D:\javaSt2021\task06//src//main//resources//threads.txt]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[10]]>
              </value>
            </param>
          </params>
          <exception class="by.training.task06.service.ServiceException">
            <message>
              <![CDATA[wrong_data_in_file]]>
            </message>
            <full-stacktrace>
              <![CDATA[by.training.task06.service.ServiceException: wrong_data_in_file
at by.training.task06.service.InitiateMatrixImpl.createMatrixMemberFromString(InitiateMatrixImpl.java:85)
at by.training.task06.service.InitiateMatrixImpl.takeMatrixFromFile(InitiateMatrixImpl.java:61)
at by.training.task06.service.ThreadLongAdderService.threadLongAdderAction(ThreadLongAdderService.java:49)
at by.training.task06.service.ThreadServiceTest.threadLongAdderActionNegativeTest(ThreadServiceTest.java:126)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- by.training.task06.service.ServiceException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- threadLongAdderActionNegativeTest -->
        <test-method signature="threadLongAdderActionNegativeTest(java.lang.String,int,java.lang.String,int)[pri:0, instance:by.training.task06.service.ThreadServiceTest@66565121]" started-at="2021-07-15T18:06:50 MSK" name="threadLongAdderActionNegativeTest" description="negative for threadLongAdderAction" data-provider="NegativeForThreadService" finished-at="2021-07-15T18:06:50 MSK" duration-ms="169" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[D:\javaSt2021\task06//src//main//resources//array.txt]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[200]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[D:\javaSt2021\task06//src//main//resources//threadsWrong1.txt]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[10]]>
              </value>
            </param>
          </params>
          <exception class="by.training.task06.service.ServiceException">
            <message>
              <![CDATA[wrong_data_in_file]]>
            </message>
            <full-stacktrace>
              <![CDATA[by.training.task06.service.ServiceException: wrong_data_in_file
at by.training.task06.service.InitiateThreadLongAdder.createThreadLongAdderFromString(InitiateThreadLongAdder.java:76)
at by.training.task06.service.InitiateThreadLongAdder.takeThreadsFromFile(InitiateThreadLongAdder.java:53)
at by.training.task06.service.ThreadLongAdderService.threadLongAdderAction(ThreadLongAdderService.java:59)
at by.training.task06.service.ThreadServiceTest.threadLongAdderActionNegativeTest(ThreadServiceTest.java:126)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- by.training.task06.service.ServiceException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- threadLongAdderActionNegativeTest -->
        <test-method signature="threadLongAdderActionNegativeTest(java.lang.String,int,java.lang.String,int)[pri:0, instance:by.training.task06.service.ThreadServiceTest@66565121]" started-at="2021-07-15T18:06:50 MSK" name="threadLongAdderActionNegativeTest" description="negative for threadLongAdderAction" data-provider="NegativeForThreadService" finished-at="2021-07-15T18:06:50 MSK" duration-ms="126" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[D:\javaSt2021\task06//src//main//resources//array.txt]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[200]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[D:\javaSt2021\task06//src//main//resources//threadsWrong2.txt]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[10]]>
              </value>
            </param>
          </params>
          <exception class="by.training.task06.service.ServiceException">
            <message>
              <![CDATA[wrong_data_in_file]]>
            </message>
            <full-stacktrace>
              <![CDATA[by.training.task06.service.ServiceException: wrong_data_in_file
at by.training.task06.service.InitiateThreadLongAdder.createThreadLongAdderFromString(InitiateThreadLongAdder.java:76)
at by.training.task06.service.InitiateThreadLongAdder.takeThreadsFromFile(InitiateThreadLongAdder.java:53)
at by.training.task06.service.ThreadLongAdderService.threadLongAdderAction(ThreadLongAdderService.java:59)
at by.training.task06.service.ThreadServiceTest.threadLongAdderActionNegativeTest(ThreadServiceTest.java:126)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- by.training.task06.service.ServiceException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- threadLongAdderActionNegativeTest -->
        <test-method signature="threadLongAdderActionNegativeTest(java.lang.String,int,java.lang.String,int)[pri:0, instance:by.training.task06.service.ThreadServiceTest@66565121]" started-at="2021-07-15T18:06:50 MSK" name="threadLongAdderActionNegativeTest" description="negative for threadLongAdderAction" data-provider="NegativeForThreadService" finished-at="2021-07-15T18:06:50 MSK" duration-ms="20" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[D:\javaSt2021\task06//src//main//resources//arrayWrong1.txt]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[200]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[D:\javaSt2021\task06//src//main//resources//threadsWrong1.txt]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[10]]>
              </value>
            </param>
          </params>
          <exception class="by.training.task06.service.ServiceException">
            <message>
              <![CDATA[wrong_data_in_file]]>
            </message>
            <full-stacktrace>
              <![CDATA[by.training.task06.service.ServiceException: wrong_data_in_file
at by.training.task06.service.InitiateMatrixImpl.createMatrixMemberFromString(InitiateMatrixImpl.java:85)
at by.training.task06.service.InitiateMatrixImpl.takeMatrixFromFile(InitiateMatrixImpl.java:61)
at by.training.task06.service.ThreadLongAdderService.threadLongAdderAction(ThreadLongAdderService.java:49)
at by.training.task06.service.ThreadServiceTest.threadLongAdderActionNegativeTest(ThreadServiceTest.java:126)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- by.training.task06.service.ServiceException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- threadLongAdderActionNegativeTest -->
        <test-method signature="threadLongAdderActionNegativeTest(java.lang.String,int,java.lang.String,int)[pri:0, instance:by.training.task06.service.ThreadServiceTest@66565121]" started-at="2021-07-15T18:06:50 MSK" name="threadLongAdderActionNegativeTest" description="negative for threadLongAdderAction" data-provider="NegativeForThreadService" finished-at="2021-07-15T18:06:50 MSK" duration-ms="5" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[D:\javaSt2021\task06wrong]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[200]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[D:\javaSt2021\task06//src//main//resources//threadsWrong2.txt]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[10]]>
              </value>
            </param>
          </params>
          <exception class="by.training.task06.service.ServiceException">
            <message>
              <![CDATA[wrong_path]]>
            </message>
            <full-stacktrace>
              <![CDATA[by.training.task06.service.ServiceException: wrong_path
at by.training.task06.service.InitiateMatrixImpl.takeMatrixFromFile(InitiateMatrixImpl.java:68)
at by.training.task06.service.ThreadLongAdderService.threadLongAdderAction(ThreadLongAdderService.java:49)
at by.training.task06.service.ThreadServiceTest.threadLongAdderActionNegativeTest(ThreadServiceTest.java:126)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- by.training.task06.service.ServiceException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- threadLongAdderActionNegativeTest -->
        <test-method signature="threadLongAdderActionNegativeTest(java.lang.String,int,java.lang.String,int)[pri:0, instance:by.training.task06.service.ThreadServiceTest@66565121]" started-at="2021-07-15T18:06:50 MSK" name="threadLongAdderActionNegativeTest" description="negative for threadLongAdderAction" data-provider="NegativeForThreadService" finished-at="2021-07-15T18:06:50 MSK" duration-ms="7" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[D:\javaSt2021\task06//src//main//resources//arrayWrong1.txt]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[200]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[D:\javaSt2021\task06wrong]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[10]]>
              </value>
            </param>
          </params>
          <exception class="by.training.task06.service.ServiceException">
            <message>
              <![CDATA[wrong_data_in_file]]>
            </message>
            <full-stacktrace>
              <![CDATA[by.training.task06.service.ServiceException: wrong_data_in_file
at by.training.task06.service.InitiateMatrixImpl.createMatrixMemberFromString(InitiateMatrixImpl.java:85)
at by.training.task06.service.InitiateMatrixImpl.takeMatrixFromFile(InitiateMatrixImpl.java:61)
at by.training.task06.service.ThreadLongAdderService.threadLongAdderAction(ThreadLongAdderService.java:49)
at by.training.task06.service.ThreadServiceTest.threadLongAdderActionNegativeTest(ThreadServiceTest.java:126)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- by.training.task06.service.ServiceException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- threadLongAdderActionNegativeTest -->
        <test-method signature="threadLongAdderActionNegativeTest(java.lang.String,int,java.lang.String,int)[pri:0, instance:by.training.task06.service.ThreadServiceTest@66565121]" started-at="2021-07-15T18:06:50 MSK" name="threadLongAdderActionNegativeTest" description="negative for threadLongAdderAction" data-provider="NegativeForThreadService" finished-at="2021-07-15T18:06:50 MSK" duration-ms="4" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[D:\javaSt2021\task06//src//main//resources//array.txt]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[251]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[D:\javaSt2021\task06//src//main//resources//threads.txt]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[10]]>
              </value>
            </param>
          </params>
          <exception class="by.training.task06.service.ServiceException">
            <message>
              <![CDATA[wrong_incoming_data]]>
            </message>
            <full-stacktrace>
              <![CDATA[by.training.task06.service.ServiceException: wrong_incoming_data
at by.training.task06.service.ThreadLongAdderService.checkThreadsArraysNumbers(ThreadLongAdderService.java:130)
at by.training.task06.service.ThreadLongAdderService.threadLongAdderAction(ThreadLongAdderService.java:42)
at by.training.task06.service.ThreadServiceTest.threadLongAdderActionNegativeTest(ThreadServiceTest.java:126)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- by.training.task06.service.ServiceException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- threadLongAdderActionNegativeTest -->
        <test-method signature="threadLongAdderActionNegativeTest(java.lang.String,int,java.lang.String,int)[pri:0, instance:by.training.task06.service.ThreadServiceTest@66565121]" started-at="2021-07-15T18:06:50 MSK" name="threadLongAdderActionNegativeTest" description="negative for threadLongAdderAction" data-provider="NegativeForThreadService" finished-at="2021-07-15T18:06:50 MSK" duration-ms="4" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[D:\javaSt2021\task06//src//main//resources//array.txt]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[D:\javaSt2021\task06//src//main//resources//threads.txt]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[10]]>
              </value>
            </param>
          </params>
          <exception class="by.training.task06.service.ServiceException">
            <message>
              <![CDATA[wrong_incoming_data]]>
            </message>
            <full-stacktrace>
              <![CDATA[by.training.task06.service.ServiceException: wrong_incoming_data
at by.training.task06.service.ThreadLongAdderService.checkThreadsArraysNumbers(ThreadLongAdderService.java:130)
at by.training.task06.service.ThreadLongAdderService.threadLongAdderAction(ThreadLongAdderService.java:42)
at by.training.task06.service.ThreadServiceTest.threadLongAdderActionNegativeTest(ThreadServiceTest.java:126)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- by.training.task06.service.ServiceException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- threadLongAdderActionNegativeTest -->
        <test-method signature="threadLongAdderActionNegativeTest(java.lang.String,int,java.lang.String,int)[pri:0, instance:by.training.task06.service.ThreadServiceTest@66565121]" started-at="2021-07-15T18:06:50 MSK" name="threadLongAdderActionNegativeTest" description="negative for threadLongAdderAction" data-provider="NegativeForThreadService" finished-at="2021-07-15T18:06:50 MSK" duration-ms="3" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[D:\javaSt2021\task06//src//main//resources//array.txt]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[200]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[D:\javaSt2021\task06//src//main//resources//threads.txt]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[101]]>
              </value>
            </param>
          </params>
          <exception class="by.training.task06.service.ServiceException">
            <message>
              <![CDATA[wrong_incoming_data]]>
            </message>
            <full-stacktrace>
              <![CDATA[by.training.task06.service.ServiceException: wrong_incoming_data
at by.training.task06.service.ThreadLongAdderService.checkThreadsArraysNumbers(ThreadLongAdderService.java:130)
at by.training.task06.service.ThreadLongAdderService.threadLongAdderAction(ThreadLongAdderService.java:42)
at by.training.task06.service.ThreadServiceTest.threadLongAdderActionNegativeTest(ThreadServiceTest.java:126)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- by.training.task06.service.ServiceException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- threadLongAdderActionNegativeTest -->
        <test-method signature="threadLongAdderActionNegativeTest(java.lang.String,int,java.lang.String,int)[pri:0, instance:by.training.task06.service.ThreadServiceTest@66565121]" started-at="2021-07-15T18:06:50 MSK" name="threadLongAdderActionNegativeTest" description="negative for threadLongAdderAction" data-provider="NegativeForThreadService" finished-at="2021-07-15T18:06:50 MSK" duration-ms="3" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[D:\javaSt2021\task06//src//main//resources//array.txt]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[10]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[D:\javaSt2021\task06//src//main//resources//threads.txt]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[0]]>
              </value>
            </param>
          </params>
          <exception class="by.training.task06.service.ServiceException">
            <message>
              <![CDATA[wrong_incoming_data]]>
            </message>
            <full-stacktrace>
              <![CDATA[by.training.task06.service.ServiceException: wrong_incoming_data
at by.training.task06.service.ThreadLongAdderService.checkThreadsArraysNumbers(ThreadLongAdderService.java:130)
at by.training.task06.service.ThreadLongAdderService.threadLongAdderAction(ThreadLongAdderService.java:42)
at by.training.task06.service.ThreadServiceTest.threadLongAdderActionNegativeTest(ThreadServiceTest.java:126)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- by.training.task06.service.ServiceException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- threadLongAdderActionNegativeTest -->
      </class> <!-- by.training.task06.service.ThreadServiceTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
